services:

  app:
    build:
      context: node
    image: dockermactur/node:fullcycle
    container_name: app
    entrypoint: sh -c "npm install && npm run dev"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "8080:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9.2.0
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD" ]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - node-network

networks:
  node-network:
    driver: bridge